on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: creditsalesregistry.azurecr.io
        username: ${{ secrets.acr_creditsalesregistry_username }}
        password: ${{ secrets.acr_creditsalesregistry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/app" -f  "app/Dockerfile" -t creditsalesregistry.azurecr.io/creditsalescluster:${{ github.sha }} --label dockerfile-path=app/Dockerfile
        docker push creditsalesregistry.azurecr.io/creditsalescluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_creditsalescluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep creditsalesclusterae40 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace creditsalesclusterae40`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: creditsalesclusterae40
        container-registry-url: creditsalesregistry.azurecr.io
        container-registry-username: ${{ secrets.acr_creditsalesregistry_username }}
        container-registry-password: ${{ secrets.acr_creditsalesregistry_password }}
        secret-name: creditsalescdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: creditsalesclusterae40
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          creditsalesregistry.azurecr.io/creditsalescluster:${{ github.sha }}
        imagepullsecrets: |
          creditsalescdockerauth
